### ISSUE TITLE
Sequences of different lengths

### ISSUE THREAD

**Issue by milkschen** [tsnorri/founder-sequences#1]
Hi,

I'm interested in using the founder-sequences algorithm to generate a compact representation of pan-genome. I wonder if this algorithm supports sequences of different lengths since there might be indels between the sequences.

Thanks in advance!

**Comment by tsnorri** [comment]
Hi! Unfortunately the input needs to be a multiple alignment. If you have variant calls, the input can be generated with [vcf2multialign](https://github.com/tsnorri/vcf2multialign/), though.

**Comment by milkschen** [comment]
Thank you for the quick response. I'll try that!
